-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "leftAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "leftReason" TEXT;

-- AlterTable
ALTER TABLE "StudentProfile" ADD COLUMN IF NOT EXISTS "isFormer" BOOLEAN NOT NULL DEFAULT false;
